language: go
sudo: false

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - tip

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -v ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci

after_success:
  - export CODECOV_TOKEN="1072385b-73f1-4896-9473-7046dd354862"
  - bash <(curl -s https://codecov.io/bash)
